use estore;

create table if not exists country (
   iso2 char(2) not null,
   name varchar(50) not null,
   primary key (iso2)
) default charset=utf8;

select * from country;

/*
 Seed Countries
 */
insert into country values ('AF', 'Afghanistan');
insert into country values ('AL', 'Albania');
insert into country values ('DZ', 'Algeria');
insert into country values ('DS', 'American Samoa');
insert into country values ('AD', 'Andorra');
insert into country values ('AO', 'Angola');
insert into country values ('AI', 'Anguilla');
insert into country values ('AQ', 'Antarctica');
insert into country values ('AG', 'Antigua and Barbuda');
insert into country values ('AR', 'Argentina');
insert into country values ('AM', 'Armenia');
insert into country values ('AW', 'Aruba');
insert into country values ('AU', 'Australia');
insert into country values ('AT', 'Austria');
insert into country values ('AZ', 'Azerbaijan');
insert into country values ('BS', 'Bahamas');
insert into country values ('BH', 'Bahrain');
insert into country values ('BD', 'Bangladesh');
insert into country values ('BB', 'Barbados');
insert into country values ('BY', 'Belarus');
insert into country values ('BE', 'Belgium');
insert into country values ('BZ', 'Belize');
insert into country values ('BJ', 'Benin');
insert into country values ('BM', 'Bermuda');
insert into country values ('BT', 'Bhutan');
insert into country values ('BO', 'Bolivia');
insert into country values ('BA', 'Bosnia and Herzegovina');
insert into country values ('BW', 'Botswana');
insert into country values ('BV', 'Bouvet Island');
insert into country values ('BR', 'Brazil');
insert into country values ('IO', 'British Indian Ocean Territory');
insert into country values ('BN', 'Brunei Darussalam');
insert into country values ('BG', 'Bulgaria');
insert into country values ('BF', 'Burkina Faso');
insert into country values ('BI', 'Burundi');
insert into country values ('KH', 'Cambodia');
insert into country values ('CM', 'Cameroon');
insert into country values ('CA', 'Canada');
insert into country values ('CV', 'Cape Verde');
insert into country values ('KY', 'Cayman Islands');
insert into country values ('CF', 'Central African Republic');
insert into country values ('TD', 'Chad');
insert into country values ('CL', 'Chile');
insert into country values ('CN', 'China');
insert into country values ('CX', 'Christmas Island');
insert into country values ('CC', 'Cocos (Keeling) Islands');
insert into country values ('CO', 'Colombia');
insert into country values ('KM', 'Comoros');
insert into country values ('CD', 'Democratic Republic of the Congo');
insert into country values ('CG', 'Republic of Congo');
insert into country values ('CK', 'Cook Islands');
insert into country values ('CR', 'Costa Rica');
insert into country values ('HR', 'Croatia (Hrvatska)');
insert into country values ('CU', 'Cuba');
insert into country values ('CY', 'Cyprus');
insert into country values ('CZ', 'Czech Republic');
insert into country values ('DK', 'Denmark');
insert into country values ('DJ', 'Djibouti');
insert into country values ('DM', 'Dominica');
insert into country values ('DO', 'Dominican Republic');
insert into country values ('TP', 'East Timor');
insert into country values ('EC', 'Ecuador');
insert into country values ('EG', 'Egypt');
insert into country values ('SV', 'El Salvador');
insert into country values ('GQ', 'Equatorial Guinea');
insert into country values ('ER', 'Eritrea');
insert into country values ('EE', 'Estonia');
insert into country values ('ET', 'Ethiopia');
insert into country values ('FK', 'Falkland Islands (Malvinas)');
insert into country values ('FO', 'Faroe Islands');
insert into country values ('FJ', 'Fiji');
insert into country values ('FI', 'Finland');
insert into country values ('FR', 'France');
insert into country values ('FX', 'France, Metropolitan');
insert into country values ('GF', 'French Guiana');
insert into country values ('PF', 'French Polynesia');
insert into country values ('TF', 'French Southern Territories');
insert into country values ('GA', 'Gabon');
insert into country values ('GM', 'Gambia');
insert into country values ('GE', 'Georgia');
insert into country values ('DE', 'Germany');
insert into country values ('GH', 'Ghana');
insert into country values ('GI', 'Gibraltar');
insert into country values ('GK', 'Guernsey');
insert into country values ('GR', 'Greece');
insert into country values ('GL', 'Greenland');
insert into country values ('GD', 'Grenada');
insert into country values ('GP', 'Guadeloupe');
insert into country values ('GU', 'Guam');
insert into country values ('GT', 'Guatemala');
insert into country values ('GN', 'Guinea');
insert into country values ('GW', 'Guinea-Bissau');
insert into country values ('GY', 'Guyana');
insert into country values ('HT', 'Haiti');
insert into country values ('HM', 'Heard and Mc Donald Islands');
insert into country values ('HN', 'Honduras');
insert into country values ('HK', 'Hong Kong');
insert into country values ('HU', 'Hungary');
insert into country values ('IS', 'Iceland');
insert into country values ('IN', 'India');
insert into country values ('IM', 'Isle of Man');
insert into country values ('ID', 'Indonesia');
insert into country values ('IR', 'Iran (Islamic Republic of)');
insert into country values ('IQ', 'Iraq');
insert into country values ('IE', 'Ireland');
insert into country values ('IL', 'Israel');
insert into country values ('IT', 'Italy');
insert into country values ('CI', 'Ivory Coast');
insert into country values ('JE', 'Jersey');
insert into country values ('JM', 'Jamaica');
insert into country values ('JP', 'Japan');
insert into country values ('JO', 'Jordan');
insert into country values ('KZ', 'Kazakhstan');
insert into country values ('KE', 'Kenya');
insert into country values ('KI', 'Kiribati');
insert into country values ('KP', 'Korea, Democratic People''s Republic of');
insert into country values ('KR', 'Korea, Republic of');
insert into country values ('XK', 'Kosovo');
insert into country values ('KW', 'Kuwait');
insert into country values ('KG', 'Kyrgyzstan');
insert into country values ('LA', 'Lao People''s Democratic Republic');
insert into country values ('LV', 'Latvia');
insert into country values ('LB', 'Lebanon');
insert into country values ('LS', 'Lesotho');
insert into country values ('LR', 'Liberia');
insert into country values ('LY', 'Libyan Arab Jamahiriya');
insert into country values ('LI', 'Liechtenstein');
insert into country values ('LT', 'Lithuania');
insert into country values ('LU', 'Luxembourg');
insert into country values ('MO', 'Macau');
insert into country values ('MK', 'North Macedonia');
insert into country values ('MG', 'Madagascar');
insert into country values ('MW', 'Malawi');
insert into country values ('MY', 'Malaysia');
insert into country values ('MV', 'Maldives');
insert into country values ('ML', 'Mali');
insert into country values ('MT', 'Malta');
insert into country values ('MH', 'Marshall Islands');
insert into country values ('MQ', 'Martinique');
insert into country values ('MR', 'Mauritania');
insert into country values ('MU', 'Mauritius');
insert into country values ('TY', 'Mayotte');
insert into country values ('MX', 'Mexico');
insert into country values ('FM', 'Micronesia, Federated States of');
insert into country values ('MD', 'Moldova, Republic of');
insert into country values ('MC', 'Monaco');
insert into country values ('MN', 'Mongolia');
insert into country values ('ME', 'Montenegro');
insert into country values ('MS', 'Montserrat');
insert into country values ('MA', 'Morocco');
insert into country values ('MZ', 'Mozambique');
insert into country values ('MM', 'Myanmar');
insert into country values ('NA', 'Namibia');
insert into country values ('NR', 'Nauru');
insert into country values ('NP', 'Nepal');
insert into country values ('NL', 'Netherlands');
insert into country values ('AN', 'Netherlands Antilles');
insert into country values ('NC', 'New Caledonia');
insert into country values ('NZ', 'New Zealand');
insert into country values ('NI', 'Nicaragua');
insert into country values ('NE', 'Niger');
insert into country values ('NG', 'Nigeria');
insert into country values ('NU', 'Niue');
insert into country values ('NF', 'Norfolk Island');
insert into country values ('MP', 'Northern Mariana Islands');
insert into country values ('NO', 'Norway');
insert into country values ('OM', 'Oman');
insert into country values ('PK', 'Pakistan');
insert into country values ('PW', 'Palau');
insert into country values ('PS', 'Palestine');
insert into country values ('PA', 'Panama');
insert into country values ('PG', 'Papua New Guinea');
insert into country values ('PY', 'Paraguay');
insert into country values ('PE', 'Peru');
insert into country values ('PH', 'Philippines');
insert into country values ('PN', 'Pitcairn');
insert into country values ('PL', 'Poland');
insert into country values ('PT', 'Portugal');
insert into country values ('PR', 'Puerto Rico');
insert into country values ('QA', 'Qatar');
insert into country values ('RE', 'Reunion');
insert into country values ('RO', 'Romania');
insert into country values ('RU', 'Russian Federation');
insert into country values ('RW', 'Rwanda');
insert into country values ('KN', 'Saint Kitts and Nevis');
insert into country values ('LC', 'Saint Lucia');
insert into country values ('VC', 'Saint Vincent and the Grenadines');
insert into country values ('WS', 'Samoa');
insert into country values ('SM', 'San Marino');
insert into country values ('ST', 'Sao Tome and Principe');
insert into country values ('SA', 'Saudi Arabia');
insert into country values ('SN', 'Senegal');
insert into country values ('RS', 'Serbia');
insert into country values ('SC', 'Seychelles');
insert into country values ('SL', 'Sierra Leone');
insert into country values ('SG', 'Singapore');
insert into country values ('SK', 'Slovakia');
insert into country values ('SI', 'Slovenia');
insert into country values ('SB', 'Solomon Islands');
insert into country values ('SO', 'Somalia');
insert into country values ('ZA', 'South Africa');
insert into country values ('GS', 'South Georgia South Sandwich Islands');
insert into country values ('SS', 'South Sudan');
insert into country values ('ES', 'Spain');
insert into country values ('LK', 'Sri Lanka');
insert into country values ('SH', 'St. Helena');
insert into country values ('PM', 'St. Pierre and Miquelon');
insert into country values ('SD', 'Sudan');
insert into country values ('SR', 'Suriname');
insert into country values ('SJ', 'Svalbard and Jan Mayen Islands');
insert into country values ('SZ', 'Swaziland');
insert into country values ('SE', 'Sweden');
insert into country values ('CH', 'Switzerland');
insert into country values ('SY', 'Syrian Arab Republic');
insert into country values ('TW', 'Taiwan');
insert into country values ('TJ', 'Tajikistan');
insert into country values ('TZ', 'Tanzania, United Republic of');
insert into country values ('TH', 'Thailand');
insert into country values ('TG', 'Togo');
insert into country values ('TK', 'Tokelau');
insert into country values ('TO', 'Tonga');
insert into country values ('TT', 'Trinidad and Tobago');
insert into country values ('TN', 'Tunisia');
insert into country values ('TR', 'Turkey');
insert into country values ('TM', 'Turkmenistan');
insert into country values ('TC', 'Turks and Caicos Islands');
insert into country values ('TV', 'Tuvalu');
insert into country values ('UG', 'Uganda');
insert into country values ('UA', 'Ukraine');
insert into country values ('AE', 'United Arab Emirates');
insert into country values ('GB', 'United Kingdom');
insert into country values ('US', 'United States');
insert into country values ('UM', 'United States minor outlying islands');
insert into country values ('UY', 'Uruguay');
insert into country values ('UZ', 'Uzbekistan');
insert into country values ('VU', 'Vanuatu');
insert into country values ('VA', 'Vatican City State');
insert into country values ('VE', 'Venezuela');
insert into country values ('VN', 'Vietnam');
insert into country values ('VG', 'Virgin Islands (British)');
insert into country values ('VI', 'Virgin Islands (U.S.)');
insert into country values ('WF', 'Wallis and Futuna Islands');
insert into country values ('EH', 'Western Sahara');
insert into country values ('YE', 'Yemen');
insert into country values ('ZM', 'Zambia');
insert into country values ('ZW', 'Zimbabwe');